apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frontend-prod

resources:
  - namespace.yaml
  - configmap-frontend.yaml
  - ../../base

patches:
  - target:
      kind: Ingress
      name: frontend
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: application-prod.local

  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: REPLACE_ME_FRONTEND_IMAGE_PROD